### ISSUE TITLE
Empty Rotation field - then drag a slider of a different rotation

### ISSUE THREAD

**Issue by iChun** [iChun/Tabula#108]
```[17:28:18] [Client thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1204) ~[EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1209) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:442) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:1.8.0_201]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_201]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_201]
	at me.ichun.mods.tabula.client.gui.window.WindowControls.elementTriggered(WindowControls.java:351) ~[WindowControls.class:?]
	at me.ichun.mods.tabula.client.gui.window.WindowControls.elementTriggered(WindowControls.java:469) ~[WindowControls.class:?]
	at me.ichun.mods.ichunutil.client.gui.window.element.ElementHoriSlider.draw(ElementHoriSlider.java:61) ~[ElementHoriSlider.class:?]
	at me.ichun.mods.ichunutil.client.gui.window.Window.draw(Window.java:131) ~[Window.class:?]
	at me.ichun.mods.tabula.client.gui.window.WindowControls.draw(WindowControls.java:250) ~[WindowControls.class:?]
	at me.ichun.mods.ichunutil.client.gui.window.IWorkspace.drawWindows(IWorkspace.java:142) ~[IWorkspace.class:?]
	at me.ichun.mods.tabula.client.gui.GuiWorkspace.drawScreen(GuiWorkspace.java:512) ~[GuiWorkspace.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1177) ~[EntityRenderer.class:?]
	... 15 more
[17:28:18] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:629]: ---- Minecraft Crash Report ----
```

**Comment by iChun** [comment]
Fixed.
