### ISSUE TITLE
Crash when there is no text in rotation field

### ISSUE THREAD

**Issue by gudenau** [iChun/Tabula#71]
When I clear a rotation flied then edit a separate one the game crashes.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 6/22/15 6:41 PM
Description: Rendering screen

java.lang.NumberFormatException: empty String
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
    at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
    at java.lang.Double.parseDouble(Double.java:538)
    at us.ichun.mods.tabula.client.gui.window.WindowControls.elementTriggered(WindowControls.java:354)
    at us.ichun.mods.ichunutil.client.gui.window.element.ElementNumberInput.changeValue(ElementNumberInput.java:405)
    at us.ichun.mods.ichunutil.client.gui.window.element.ElementNumberInput.mouseScroll(ElementNumberInput.java:94)
    at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.updateElementHovered(IWorkspace.java:193)
    at us.ichun.mods.tabula.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:568)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:461)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1078)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
    at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
    at java.lang.Double.parseDouble(Double.java:538)
    at us.ichun.mods.tabula.client.gui.window.WindowControls.elementTriggered(WindowControls.java:354)
    at us.ichun.mods.ichunutil.client.gui.window.element.ElementNumberInput.changeValue(ElementNumberInput.java:405)
    at us.ichun.mods.ichunutil.client.gui.window.element.ElementNumberInput.mouseScroll(ElementNumberInput.java:94)
    at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.updateElementHovered(IWorkspace.java:193)
    at us.ichun.mods.tabula.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:568)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:461)

-- Screen render details --
Details:
    Screen name: us.ichun.mods.tabula.client.gui.GuiWorkspace
    Mouse location: Scaled: (125, 258). Absolute: (250, 228)
    Screen size: Scaled: (683, 373). Absolute: (1366, 746). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1078)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 905025152 bytes (863 MB) / 1075838976 bytes (1026 MB) up to 2386558976 bytes (2276 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2560m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1449 8 mods loaded, 8 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.3.1449.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{11.14.3.1449} [Minecraft Forge](forge-1.8-11.14.3.1449.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{1.0.5.36} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.0.5.104} [Not Enough Items](NotEnoughItems-1.8-1.0.5.104-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{5.4.0} [iChunUtil](iChunUtil-5.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    legendset{1.0} [legendset](legendset-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Tabula{5.1.0} [Tabula](Tabula-5.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)

NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 650/PCIe/SSE2'
    Launched Version: forge-11.14.3.1449
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 650/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.30, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
```

**Comment by iChun** [comment]
I'm pretty sure I fixed this eventually. Anyway:

As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
