### ISSUE TITLE
Crash on model import

### ISSUE THREAD

**Issue by CliffracerX** [iChun/Tabula#77]
Specifically, when I try to import anything related to the Enderdragon (normal entity OR NPC from CustomNPCs)

Crash log, if it's of any use

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 7/18/15 7:58 PM
Description: Rendering screen

java.lang.NoSuchMethodError: us.ichun.module.tabula.client.model.ModelBaseDummy.render(FLjava/util/ArrayList;Ljava/util/ArrayList;FZI)V
    at us.ichun.mods.tabula.client.gui.GuiWorkspace.renderWorkspace(GuiWorkspace.java:879)
    at us.ichun.mods.tabula.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:329)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at us.ichun.mods.tabula.client.gui.GuiWorkspace.renderWorkspace(GuiWorkspace.java:879)
    at us.ichun.mods.tabula.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:329)

-- Screen render details --
Details:
    Screen name: us.ichun.mods.tabula.client.gui.GuiWorkspace
    Mouse location: Scaled: (504, 448). Absolute: (1009, 163)
    Screen size: Scaled: (960, 530). Absolute: (1920, 1060). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
//Long list of mods truncated due to it being a very long list

I'm currently using the WearMC compatible version of Tabula, I'll try using the last 1.7.10 release as well and seeing if it's there too.

**Comment by iChun** [comment]
What versions are these?

**Comment by CliffracerX** [comment]
I'm using Minecraft 1.7.10, and the WearMC modded version of Tabula 4.0.2a.

**Comment by iChun** [comment]
I'd recommend updating

**Comment by CliffracerX** [comment]
Has the save fornat changed at all between versions?

**Comment by iChun** [comment]
The save format is made so that it'll repair itself as updates come, but
you're using a very very outdated version of Tabula, so I would again,
recommend updating.

**Comment by CliffracerX** [comment]
At the moment I need the model for a 1.7.10 project, meaning being able to
import the model in 1.8 and then load the project file in 1.7.10 is what I
would be looking for.

**Comment by iChun** [comment]
Most of the code exported by the 1.8 version of the mod would still work in
1.7.10 environments.

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
