### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by SteveOriginal** [iChun/Tabula#80]
Is Possible Make A Application Of Tabula Like Techne?
I Have Windows10 And Java Is Not Compatible,I Not Play For Weeks,Other Suggestion Is Add A Block Creator Tool For Minecraft 1.8 (json Files)

**Comment by ZornTaov** [comment]
java seems to work just fine for my in Windows 10, try using ninite.com and select the java checkbox to have an easy way of installing the latest java version

**Comment by SteveOriginal** [comment]
I Try,My Minecarft Crash Vanilla Version (In Windows 7,Is Not A problem)Much Peoples Said Java Is Not Compatible In Windows 10,My Video Drivers Is Ok,I Have Much Memory,And Latest Version Of Java But Minecraft Not Work!


----Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 14/08/15 16:13
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bao.ag(SourceFile:340)
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bao.ag(SourceFile:340)

-- Initialization --
Details:
Stacktrace:
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 43231656 bytes (41 MB) / 125042688 bytes (119 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: [Blocksmith-Hybrid-1.7.zip, Pixel Reality Atmosphere.zip]
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Silvina\AppData\Roaming\.minecraft\crash-reports\crash-2015-08-14_16.13.52-client.txt
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
