### ISSUE TITLE
Crash on double click a cube while modeling

### ISSUE THREAD

**Issue by PinkaLulan** [iChun/Tabula#87]
The game sometimes crashed when I double click a cube in modeling screen.
Tabula 5.1.0 + iChunUtil 5.5.0

crash log:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2017/2/13 下午 2:39
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at us.ichun.mods.tabula.client.gui.window.WindowEditObjectMetadata.<init>(WindowEditObjectMetadata.java:43)
	at us.ichun.mods.tabula.client.gui.window.WindowModelTree.elementTriggered(WindowModelTree.java:84)
	at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree.triggerParent(ElementListTree.java:304)
	at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree$Tree.draw(ElementListTree.java:533)
	at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree.draw(ElementListTree.java:123)
	at us.ichun.mods.ichunutil.client.gui.window.Window.draw(Window.java:130)
	at us.ichun.mods.tabula.client.gui.window.WindowModelTree.draw(WindowModelTree.java:33)
	at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.drawWindows(IWorkspace.java:142)
	at us.ichun.mods.tabula.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:511)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:469)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1081)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at us.ichun.mods.tabula.client.gui.window.WindowEditObjectMetadata.<init>(WindowEditObjectMetadata.java:43)
	at us.ichun.mods.tabula.client.gui.window.WindowModelTree.elementTriggered(WindowModelTree.java:84)
	at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree.triggerParent(ElementListTree.java:304)
	at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree$Tree.draw(ElementListTree.java:533)
	at us.ichun.mods.ichunutil.client.gui.window.element.ElementListTree.draw(ElementListTree.java:123)
	at us.ichun.mods.ichunutil.client.gui.window.Window.draw(Window.java:130)
	at us.ichun.mods.tabula.client.gui.window.WindowModelTree.draw(WindowModelTree.java:33)
	at us.ichun.mods.ichunutil.client.gui.window.IWorkspace.drawWindows(IWorkspace.java:142)
	at us.ichun.mods.tabula.client.gui.GuiWorkspace.func_73863_a(GuiWorkspace.java:511)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:469)

-- Screen render details --
Details:
	Screen name: us.ichun.mods.tabula.client.gui.GuiWorkspace
	Mouse location: Scaled: (512, 432). Absolute: (1024, 184)
	Screen size: Scaled: (914, 525). Absolute: (1827, 1049). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1081)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 103061024 bytes (98 MB) / 356065280 bytes (339 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar) 
	UCHIJA	Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar) 
	UCHIJA	iChunUtil{5.5.0} [iChunUtil] (iChunUtil-5.5.0.jar) 
	UCHIJA	Tabula{5.1.0} [Tabula] (Tabula-5.1.0.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.70' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.8-forge1.8-11.14.4.1563
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.5.0 NVIDIA 375.70, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
