### ISSUE TITLE
Minecraft crashing when running Tabula in a Deobf enviroment.

### ISSUE THREAD

**Issue by MatthewWork** [iChun/Tabula#88]
Hello, I am trying to get Tabula to work from inside Eclipse. Current forge version is 11.14.4.1563. The recommended version for 1.8. The only mod in there besides the defaults is the examplemod. However, it keeps crashing. I have provided the console output. Please let me know if you need anymore details, or if I am doing something wrong.

[14:44:33] [main/INFO] [GradleStart]: Extra: []
[14:44:33] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/Matthew/.gradle/caches/minecraft/assets, --assetIndex, 1.8, --accessToken{REDACTED}, --version, 1.8, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[14:44:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:44:33] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:44:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[14:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:44:33] [main/INFO] [FML]: Forge Mod Loader version 11.14.4.1563 for Minecraft 1.8 loading
[14:44:33] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_71, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_71
[14:44:33] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[14:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[14:44:33] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[14:44:33] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[14:44:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:44:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:44:33] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[14:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:44:33] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:44:33] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[14:44:35] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[14:44:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:44:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:44:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[14:44:37] [main/INFO] [GradleStart]: Remapping AccessTransformer rules...
[14:44:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[14:44:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[14:44:37] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[14:44:39] [Client thread/INFO]: Setting user: Player572
[14:44:45] [Client thread/INFO]: LWJGL Version: 2.9.1
[14:44:46] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:246]: ---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 4/14/17 2:44 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 889154072 bytes (847 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.10.3995' Renderer: 'Intel(R) HD Graphics 4400'
[14:44:46] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[14:44:46] [Client thread/INFO] [FML]: MinecraftForge v11.14.4.1563 Initialized
[14:44:46] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[14:44:46] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[14:44:47] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[14:44:47] [Client thread/INFO] [FML]: Searching C:\Users\Matthew\Desktop\Forge1563\run\mods for mods
[14:44:52] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[14:44:53] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, examplemod, iChunUtil, Tabula] at CLIENT
[14:44:53] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, examplemod, iChunUtil, Tabula] at SERVER
[14:44:55] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Example Mod, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Tabula
[14:44:55] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[14:44:55] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[14:44:55] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[14:44:55] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[14:44:56] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[14:44:56] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[14:44:56] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Found status: UP_TO_DATE Target: null
[14:44:57] [Client thread/INFO] [FML]: Applying holder lookups
[14:44:57] [Client thread/INFO] [FML]: Holder lookups applied
[14:44:57] [Client thread/INFO] [FML]: Injecting itemstacks
[14:44:57] [Client thread/INFO] [FML]: Itemstack injection complete
[14:44:58] [Sound Library Loader/INFO]: Starting up SoundSystem...
[14:44:58] [Thread-10/INFO]: Initializing LWJGL OpenAL
[14:44:58] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[14:44:59] [Thread-10/INFO]: OpenAL initialized.
[14:44:59] [Sound Library Loader/INFO]: Sound engine started
[14:45:16] [Client thread/INFO] [FML]: Max texture size: 8192
[14:45:16] [Client thread/INFO]: Created: 16x16 textures-atlas
[14:45:18] [Client thread/INFO] [STDOUT]: [com.example.examplemod.ExampleMod:init:18]: DIRT BLOCK >> tile.dirt
[14:45:18] [Client thread/INFO] [FML]: Injecting itemstacks
[14:45:18] [Client thread/INFO] [FML]: Itemstack injection complete
[14:45:19] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from POSTINITIALIZATION to AVAILABLE. Loading cannot continue
[14:45:19] [Client thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.4.1563.jar) 
	UCHIJ	Forge{11.14.4.1563} [Minecraft Forge] (forgeSrc-1.8-11.14.4.1563.jar) 
	UCHIJ	examplemod{1.0} [Example Mod] (bin) 
	UCHIJ	iChunUtil{5.5.0} [iChunUtil] (iChunUtil-5.5.0-deobf.jar) 
	UCHIE	Tabula{5.1.0} [Tabula] (Tabula-5.1.0-deobf.jar) 
[14:45:19] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[14:45:19] [Client thread/ERROR] [FML]: Caught exception from Tabula
java.lang.NoSuchFieldError: boxName
	at us.ichun.mods.ichunutil.client.model.ModelHelper.areModelsEqual(ModelHelper.java:445) ~[ModelHelper.class:?]
	at us.ichun.mods.tabula.client.core.ClientProxy.mapModelInfo(ClientProxy.java:358) ~[ClientProxy.class:?]
	at us.ichun.mods.tabula.client.core.ClientProxy.postInit(ClientProxy.java:132) ~[ClientProxy.class:?]
	at us.ichun.mods.tabula.common.Tabula.postLoad(Tabula.java:78) ~[Tabula.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553) ~[forgeSrc-1.8-11.14.4.1563.jar:?]
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forgeSrc-1.8-11.14.4.1563.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forgeSrc-1.8-11.14.4.1563.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:736) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:356) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
[14:45:19] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:663]: ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/14/17 2:45 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: boxName
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:738)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:528)
	at net.minecraft.client.Minecraft.run(Minecraft.java:356)
	at net.minecraft.client.main.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)
Caused by: java.lang.NoSuchFieldError: boxName
	at us.ichun.mods.ichunutil.client.model.ModelHelper.areModelsEqual(ModelHelper.java:445)
	at us.ichun.mods.tabula.client.core.ClientProxy.mapModelInfo(ClientProxy.java:358)
	at us.ichun.mods.tabula.client.core.ClientProxy.postInit(ClientProxy.java:132)
	at us.ichun.mods.tabula.common.Tabula.postLoad(Tabula.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:736)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 785809448 bytes (749 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.4.1563.jar) 
	UCHIJ	Forge{11.14.4.1563} [Minecraft Forge] (forgeSrc-1.8-11.14.4.1563.jar) 
	UCHIJ	examplemod{1.0} [Example Mod] (bin) 
	UCHIJ	iChunUtil{5.5.0} [iChunUtil] (iChunUtil-5.5.0-deobf.jar) 
	UCHIE	Tabula{5.1.0} [Tabula] (Tabula-5.1.0-deobf.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.10.3995' Renderer: 'Intel(R) HD Graphics 4400'
[14:45:19] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:663]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Matthew\Desktop\Forge1563\run\.\crash-reports\crash-2017-04-14_14.45.19-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by MatthewWork** [comment]
Any suggestions?

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
